---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
library(data.table)
library(sandwich)
library(lmtest)

library(ggplot2)
library(knitr)
library(foreign)
```

```{r, include=FALSE}
d <- read.csv(file = 'data/input/ESG Survey 3_April 8, 2022_10.20.csv')
d <- data.table(d)
colnames(d)
```


```{r}
columns_to_analyse <- c('StartDate', 'EndDate', 'Duration..in.seconds.', 'Q18', 'Gender', 'Investing.knowledge','Age', 'Education', 'Household.income', 'Ethnicity', 'Stock_1', 'Q22', 'Gender.1', 'Investing.knowledge.1', 'Age.1', 'Education.1', 'Household.income.1', 'Ethnicity.1', 'Stock_1.1')
columns_temp <- c("StartDate", "EndDate", "Q18")

# colnames(d)

subset(d, select = columns_to_analyse)
nrows <- nrow(d)
# remove the metadata

d <- d[3:nrows,]
d <- d[d$StartDate >= "2022-04-06 14:33:20"]
d
```
There are `r nrows` in this analysis.

```{r}
hist(as.numeric(d$Duration..in.seconds))
```

### Covariate balance checks



```{r, include=TRUE}
d$assignment_to_treatment <-  ifelse(d$Age.1 == "", 0, 1)
d$gender_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                              d$Gender.1, d$Gender)
d$investing_knowledge_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                                           d$Investing.knowledge.1, d$Investing.knowledge)
d$age_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                           d$Age.1, d$Age)
d$education_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                           d$Education.1, d$Education)
d$household_income_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                           d$Household.income.1, d$Household.income)
d$ethnicity_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                           d$Ethnicity.1, d$Ethnicity)
d$stock_aggregated <- ifelse(d$assignment_to_treatment == 1, 
                           d$Stock_1.1, d$Stock_1)
d$assignment_to_treatment_name <- ifelse(d$assignment_to_treatment == 1, "Treatment", "Control")

d[d$gender_aggregated == ""]$gender_aggregated <- "No Data"
d[d$investing_knowledge_aggregated == ""]$investing_knowledge_aggregated <- "No Data"
d[d$age_aggregated == ""]$age_aggregated <- "No Data"
d[d$education_aggregated == ""]$education_aggregated <- "No Data"
d[d$household_income_aggregated == ""]$household_income_aggregated <- "No Data"
d[d$ethnicity_aggregated == ""]$ethnicity_aggregated <- "No Data"
d[d$stock_aggregated == ""]$stock_aggregated <- "No Data"
```

```{r}
attach(d)
plot(as.numeric(d$Duration..in.seconds), stock_aggregated, main="Scatterplot Example",
   xlab="time", ylab="conf", pch=19) 
sum(d$assignment_to_treatment)
```

### Covariate Balance Checks

```{r, include=TRUE}
# Gender
ggplot(d, aes(x = assignment_to_treatment_name, fill = gender_aggregated)) +
  geom_bar() +
  ylab("Number of Participants") +
  xlab("Assignment") +
  ggtitle("Gender Count by Assignment") +
  labs(fill = "Gender")
  scale_x_discrete(
   "Assignment to Treatment",
   labels=c("Control", "Treatment"),
   limits=factor(0, 1))

# Investing Knowledge
ggplot(d, aes(x = assignment_to_treatment, fill = investing_knowledge_aggregated)) +
  geom_bar() +
  ylab("Number of Participants") +
  xlab("Assignment") +
  ggtitle("Investing Knowledge Count by Assignment") +
  labs(fill = "Investing Knowledge")
  scale_x_discrete(
   "Assignment to Treatment",
   labels=c("Control", "Treatment"),
   limits=factor(0, 1))

# Age
ggplot(d, aes(x = assignment_to_treatment, fill = age_aggregated)) +
  geom_bar()

# Education
ggplot(d, aes(x = assignment_to_treatment, fill = education_aggregated)) +
  geom_bar()

# Household Income
ggplot(d, aes(x = assignment_to_treatment, fill = household_income_aggregated)) +
  geom_bar()

# Ethnicity
ggplot(d, aes(x = assignment_to_treatment, fill = ethnicity_aggregated)) +
  geom_bar()
```
It looks pretty balanced.

```{r}
# Represent it

ggplot(d, aes(x=as.numeric(stock_aggregated), fill=as.factor(assignment_to_treatment))) +
  geom_density( color="#e9ecef", alpha=0.2, position = 'identity') +
  scale_fill_manual(values=c("green", "red")) +
  labs(fill="Assignment to Treatment") +
  xlab("Likelihood to Invest in Presented Company") + 
  ylab("Number of Participants") +
  ggtitle("Comparison of Distributions of Outcome")
```

### Average Treatment Effect Estimate

```{r}
control <- as.numeric(d[d$assignment_to_treatment == 0]$stock_aggregated)
treatment <- as.numeric(d[d$assignment_to_treatment == 1]$stock_aggregated)

treatment_mean <- mean(treatment)
control_mean <- mean(na.omit(control))

ate <- (treatment_mean - control_mean) / control_mean

t.test(control, treatment)
```

There is a 6% decrease in the likelihood of investing in a stock given the low ESG score (3.8/10) in the treatment.

```{r}
library(sandwich)
library(lmtest)

model <- lm(as.numeric(
  stock_aggregated) ~ I(household_income_aggregated) +
    I(gender_aggregated) +
    I(age_aggregated) +
    I(ethnicity_aggregated) +
    I(investing_knowledge_aggregated),
            data=d)
coef_se <- lmtest::coefci(model, vcov.=vcovHC(model, type="HC"))
model_summary <- summary(model, se=coef_se)
model_summary
```